global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "rag-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rag-api:8000"]
